### ISSUE TITLE
Downloading script doesn't work

### ISSUE THREAD

**Issue by neeek2303** [tcwang0509/TalkingHead-1KH#1]
It seems that downloading script doesn't work, could you please provide new script or maybe link to the dataset?
For me for every file is says:

```Failed to download 5t4cwPdsVgQ
HTTP Error 429: Too Many Requests

**Comment by RayShing** [comment]
Mine is: HTTP Error 400: Bad Request

Any solution?

update: fixed by referring https://github.com/pytube/pytube/issues/1973#issuecomment-2232907131

**Comment by Ichen12** [comment]
> Mine is: HTTP Error 400: Bad Request
> 
> Any solution?
> 
> update: fixed by referring [pytube/pytube#1973 (comment)](https://github.com/pytube/pytube/issues/1973#issuecomment-2232907131)

Hi!Can you provide a script that can be used, I refer to the link, but still not

**Comment by Scaryplasmon** [comment]
i think the issues are two different ones here

> It seems that downloading script doesn't work, could you please provide new script or maybe link to the dataset? For me for every file is says:
> 
> ```
> HTTP Error 429: Too Many Requests
> ```

you might be encountering a limit with how fast u can download stuff from youtube, try adding half seconds intervals to your requests or something similar

> ine is: HTTP Error 400: Bad Request
> 
> Any solution?
> 
> update: fixed by referring [pytube/pytube#1973 (comment)](https://github.com/pytube/pytube/issues/1973#issuecomment-2232907131)

this issue for me was fixed with changing from

`from pytube import YouTube`

to 

`from pytubefix import YouTube`

you need to `pip install pytubefix` but its worth it
